import React from 'react'
import Head from 'next/head'
import styles from '../Layout/layout.module.css'

const Layout = (props: {children: React.ReactNode}) => {
  // font abel
  return (
    <>
      <Head>
        <title>Zero movies</title>
        <meta name="description" content="Generated by michael" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
         <h1>Movies</h1>
      </header>
      <main className={styles.main}>
        {props.children}
      </main>
    </>
  )
}

export default Layout