import React from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import * as S from './styles'
const Layout = (props: {children: React.ReactNode}) => {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Zero movies</title>
        <meta name="description" content="Generated by michael" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Header style={{cursor: 'pointer'}} onClick={() => router.push('/')}>
         <p style={{fontSize: '32px'}}>Movies</p>
      </S.Header>
      <S.Main >
        {props.children}
      </S.Main>
    </>
  )
}

export default Layout